# ==============================================================================
# ISOLIB DEVELOPER COCKPIT
# PowerShell Management Tool for Polyglot Logging Bridge
# ==============================================================================

$PSScriptRoot = Get-Location

function Wait-User {
    Write-Host "`nPress Enter to return to menu..." -ForegroundColor Gray
    Read-Host
}

function Check-Dependencies {
    Write-Host "--- Checking System Dependencies ---" -ForegroundColor Yellow
    $deps = @("node", "pnpm", "rustc", "cargo", "go", "bun")
    foreach ($d in $deps) {
        if (Get-Command $d -ErrorAction SilentlyContinue) {
            $v = & $d --version
            Write-Host "[OK] $d ($v)" -ForegroundColor Green
        }
        else {
            Write-Host "[MISSING] $d" -ForegroundColor Red
        }
    }
    Write-Host "`nRestoring workspace dependencies..." -ForegroundColor Cyan
    pnpm install
    Wait-User
}

function Build-TS {
    Write-Host "--- Building TypeScript SDK (Host) ---" -ForegroundColor Cyan
    Set-Location "$PSScriptRoot/packages/ts-sdk"
    pnpm run build
    Set-Location $PSScriptRoot
    Wait-User
}

function Build-Rust {
    Write-Host "--- Building Rust NAPI Module ---" -ForegroundColor Magenta
    
    # Define Paths
    $rustDir = "$PSScriptRoot/packages/rust-sdk"
    $srcNative = "$PSScriptRoot/packages/ts-sdk/src/native"
    $distNative = "$PSScriptRoot/packages/ts-sdk/dist/native"

    # 1. Pre-build Cleanup
    Write-Host "🧹 Cleaning pre-existing artifacts..." -ForegroundColor Gray
    Set-Location $rustDir
    
    # Remove Rust build folder and local artifacts
    if (Test-Path "./target") { Remove-Item -Recurse -Force "./target" }
    Remove-Item -Force "*.node", "index.d.ts" -ErrorAction SilentlyContinue

    # Remove existing artifacts from the TS-SDK directories
    Remove-Item -Force "$srcNative/index.node", "$srcNative/index.d.ts" -ErrorAction SilentlyContinue
    Remove-Item -Force "$distNative/index.node", "$distNative/index.d.ts" -ErrorAction SilentlyContinue

    # 2. Execute the build
    Write-Host "🚀 Running NAPI build..." -ForegroundColor Cyan
    npx napi build --release --platform
    
    # 3. Check if the build succeeded
    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ Build failed! Deployment aborted." -ForegroundColor Red
        Set-Location $PSScriptRoot
        Wait-User
        return
    }

    # 4. Ensure directories exist
    if (-not (Test-Path $srcNative)) { New-Item -ItemType Directory -Path $srcNative -Force | Out-Null }
    if (-not (Test-Path $distNative)) { New-Item -ItemType Directory -Path $distNative -Force | Out-Null }

    # 5. Deploy New Artifacts
    # We use a wildcard to capture the platform-specific .node file generated by napi-rs
    Copy-Item "index.d.ts" -Destination "$srcNative/index.d.ts" -Force
    Copy-Item "*.node" -Destination "$srcNative/index.node" -Force
    Copy-Item "*.node" -Destination "$distNative/index.node" -Force
    
    Set-Location $PSScriptRoot
    Write-Host "✅ Clean build successful. Native bridge deployed to src and dist." -ForegroundColor Green
    Wait-User
}

function Build-Go {
    Write-Host "--- Building Go SDK (Guest - C-Shared) ---" -ForegroundColor Cyan
    Set-Location "$PSScriptRoot/packages/go-sdk"
    # Placeholder for future C-shared build logic
    go build ./...
    Set-Location $PSScriptRoot
    Write-Host "Success: Go packages vetted/built." -ForegroundColor Green
    Wait-User
}

function Run-Guest-Tests {
    Write-Host "--- Running Guest SDK Tests (Rust & Go) ---" -ForegroundColor Yellow
    Write-Host "[Rust] Running cargo test..." -ForegroundColor Gray
    Set-Location "$PSScriptRoot/packages/rust-sdk"
    cargo test
    
    Write-Host "`n[Go] Running go test..." -ForegroundColor Gray
    Set-Location "$PSScriptRoot/packages/go-sdk"
    go test ./...
    
    Set-Location $PSScriptRoot
    Wait-User
}

function Run-TS-Tests {
    Write-Host "--- Running TypeScript Vitest Suite ---" -ForegroundColor Yellow
    Set-Location "$PSScriptRoot/packages/ts-sdk"
    # Run vitest directly to avoid pnpm filter issues
    npx vitest run
    Set-Location $PSScriptRoot
    Wait-User
}

function Run-Example {
    $engine = Read-Host "Run with (N)ode or (B)un?"
    Set-Location "$PSScriptRoot/examples/node-example"
    
    if ($engine.ToUpper() -eq 'B') {
        Write-Host "Launching with Bun (Runtime Transpilation)..." -ForegroundColor Cyan
        bun src/index.ts
    }
    else {
        Write-Host "Building and Launching with Node.js (ESM)..." -ForegroundColor Green
        pnpm run build
        node dist/index.js
    }
    
    Set-Location $PSScriptRoot
    Wait-User
}

function Clean-Artifacts {
    Write-Host "--- Wiping Build Artifacts & Node Modules ---" -ForegroundColor Red
    
    $targets = @(
        "$PSScriptRoot/packages/ts-sdk/dist",
        "$PSScriptRoot/packages/ts-sdk/node_modules",
        "$PSScriptRoot/packages/rust-sdk/target",
        "$PSScriptRoot/packages/rust-sdk/node_modules",
        "$PSScriptRoot/examples/node-example/dist",
        "$PSScriptRoot/examples/node-example/node_modules",
        "$PSScriptRoot/pnpm-lock.yaml"
    )

    foreach ($target in $targets) {
        if (Test-Path $target) {
            Write-Host "Removing: $target" -ForegroundColor Gray
            Remove-Item -Recurse -Force $target -ErrorAction SilentlyContinue
        }
    }

    Write-Host "Cleanup Complete." -ForegroundColor Green
    Write-Host "--- Re-installing Dependencies (Fresh Slate) ---" -ForegroundColor Cyan
    pnpm install
    
    Wait-User
}

function Run-Linter {
    Write-Host "--- Running Polyglot Linting Pass ---" -ForegroundColor Yellow
    
    Write-Host "[TS] Running ESLint..." -ForegroundColor Cyan
    Set-Location "$PSScriptRoot/packages/ts-sdk"
    try { pnpm run lint } catch { Write-Host "TS Linting failed." -ForegroundColor Red }
    
    Write-Host "`n[Rust] Running Clippy..." -ForegroundColor Cyan
    Set-Location "$PSScriptRoot/packages/rust-sdk"
    cargo clippy -- -D warnings
    
    Write-Host "`n[Go] Running Go Vet..." -ForegroundColor Cyan
    Set-Location "$PSScriptRoot/packages/go-sdk"
    go vet ./...
    
    Set-Location $PSScriptRoot
    Wait-User
}

function Verify-Binary {
    Write-Host "--- Verifying Native Bridge Status ---" -ForegroundColor Yellow
    
    $paths = @(
        "$PSScriptRoot/packages/ts-sdk/src/native/index.node",
        "$PSScriptRoot/packages/ts-sdk/dist/native/index.node"
    )

    foreach ($binPath in $paths) {
        if (Test-Path $binPath) {
            $size = (Get-Item $binPath).Length
            Write-Host "[OK] Found at: $binPath ($size bytes)" -ForegroundColor Green
        }
        else {
            Write-Host "[FAIL] Missing at: $binPath" -ForegroundColor Red
        }
    }
    Wait-User
}

# --- Main Menu Loop ---
do {
    Clear-Host
    Write-Host "================================================" -ForegroundColor Gray
    Write-Host "             ISOLIB DEVELOPER COCKPIT           " -ForegroundColor White
    Write-Host "================================================" -ForegroundColor Gray
    Write-Host " 1. [Setup]  Check & Install Dependencies"
    Write-Host " 2. [Build]  TypeScript SDK (Host)"
    Write-Host " 3. [Build]  Rust SDK (Guest - Shared Lib)"
    Write-Host " 4. [Build]  Go SDK (Guest - C-Shared)"
    Write-Host " 5. [Test]   Run Guest SDK Tests (Rust & Go)"
    Write-Host " 6. [Test]   Run TS Tests (Vitest)"
    Write-Host " 7. [Run]    Launch Node Example App"
    Write-Host " 8. [Clean]  Wipe Build Artifacts & Re-install"
    Write-Host " 9. [Lint]   Run Polyglot Linter (TS, Rust, Go)"
    Write-Host " V. [Verify] Check FFI Binary Status"
    Write-Host "------------------------------------------------"
    Write-Host " Q. Quit"
    Write-Host "================================================"
    
    $choice = (Read-Host "Select Option").ToUpper()

    switch ($choice) {
        '1' { Check-Dependencies }
        '2' { Build-TS }
        '3' { Build-Rust }
        '4' { Build-Go }
        '5' { Run-Guest-Tests }
        '6' { Run-TS-Tests }
        '7' { Run-Example }
        '8' { Clean-Artifacts }
        '9' { Run-Linter }
        'V' { Verify-Binary }
        'Q' { exit }
    }
} while ($true)